// Clinician-facing report — a structured summary a psychiatrist can read in 15 minutes.
// Privacy-first: generated on-device, user-initiated, never sent anywhere.
// Designed for PDF output via generatePdfBlob in exportReport.ts.

const SEPARATOR = "-".repeat(40);
const DISCLAIMER = "Generated by NilaMind — not a clinical or diagnostic tool. For informational use only. This summary is a self-report aid for your conversation with a clinician, not a diagnosis or medical record.";

export interface AssessmentTrajectoryEntry {
  date: string; // YYYY-MM-DD
  total: number;
  severity: string; // e.g. "mild", "moderate"
}

export interface AssessmentTrajectory {
  instrument: string; // e.g. "PHQ-9", "GAD-7"
  entries: AssessmentTrajectoryEntry[];
}

export interface ClinicianMedication {
  name: string;
  dose: string;
  adherenceRate: number; // 0–100
  commonSideEffects: string[];
}

export interface ClinicianEpisodeSummary {
  count: number;
  byTimeOfDay: string; // e.g. "evening (2), afternoon (1)"
  avgDurationMin: number | null;
}

export interface ClinicianReportInput {
  periodLabel: string; // e.g. "Week ending 2026-07-12" or "Month ending 2026-07-12"
  periodDays: number; // 7 or 30
  totalCheckins: number;
  daysActive: number;
  avgIntensity: number | null;
  avgSleepHours: number | null;
  circadianScore: number | null;
  socialRhythmVariability: number | null;
  assessmentTrajectories: AssessmentTrajectory[];
  medications: ClinicianMedication[];
  episodes: ClinicianEpisodeSummary;
  protocolsCompleted: number;
  nilaSessions: number;
  featuresUsed: string[];
}

function trendLabel(entries: AssessmentTrajectoryEntry[]): string | null {
  if (entries.length < 2) return null;
  const first = entries[0].total;
  const last = entries[entries.length - 1].total;
  const diff = first - last;
  if (Math.abs(diff) < 3) return "stable";
  return diff > 0 ? "improving" : "worsening";
}

export function buildClinicianReport(input: ClinicianReportInput): string {
  const lines: string[] = [];

  lines.push("NilaMind Clinician Summary");
  lines.push(input.periodLabel);
  lines.push(`  ${input.periodDays}-day report · generated from on-device data`);
  lines.push(SEPARATOR);
  lines.push("");

  // Check-ins
  lines.push("Check-ins");
  lines.push(`  Total: ${input.totalCheckins}`);
  lines.push(`  Active days: ${input.daysActive}/${input.periodDays}`);
  if (input.avgIntensity != null) {
    lines.push(`  Avg distress intensity: ${input.avgIntensity.toFixed(1)}/10`);
  }
  lines.push("");

  // Sleep & circadian
  if (input.avgSleepHours != null || input.circadianScore != null || input.socialRhythmVariability != null) {
    lines.push("Sleep & Circadian Rhythm");
    if (input.avgSleepHours != null) lines.push(`  Avg sleep: ${input.avgSleepHours.toFixed(1)}h`);
    if (input.circadianScore != null) lines.push(`  Sleep regularity score: ${input.circadianScore}/100 (higher = steadier)`);
    if (input.socialRhythmVariability != null) lines.push(`  Social rhythm variability: ±${input.socialRhythmVariability} min (lower = more regular)`);
    lines.push("");
  }

  // Assessment trajectories
  if (input.assessmentTrajectories.length > 0) {
    lines.push("Screening Trajectories (PHQ-9 / GAD-7)");
    for (const traj of input.assessmentTrajectories) {
      const trend = trendLabel(traj.entries);
      const vals = traj.entries.map((e) => `${e.date} = ${e.total} (${e.severity})`).join("; ");
      lines.push(`  ${traj.instrument}: ${vals}`);
      if (trend) lines.push(`    Trend: ${trend}`);
    }
    lines.push("  Note: PHQ-9 change >=5 points or GAD-7 change >=4 points is considered clinically meaningful.");
    lines.push("");
  } else {
    lines.push("Screening Trajectories");
    lines.push("  No assessments recorded in this period.");
    lines.push("");
  }

  // Medication adherence
  if (input.medications.length > 0) {
    lines.push("Medication Adherence");
    for (const med of input.medications) {
      const se = med.commonSideEffects.length > 0 ? ` · side effects: ${med.commonSideEffects.join(", ")}` : "";
      lines.push(`  ${med.name} ${med.dose} — ${med.adherenceRate}% adherence${se}`);
    }
    if (input.medications.length > 1) {
      const avg = Math.round(input.medications.reduce((s, m) => s + m.adherenceRate, 0) / input.medications.length);
      lines.push(`  Overall adherence: ${avg}%`);
    }
    lines.push("");
  } else {
    lines.push("Medication Adherence");
    lines.push("  No medications tracked in this period.");
    lines.push("");
  }

  // Episodes
  if (input.episodes.count > 0) {
    lines.push("Episode Log");
    lines.push(`  Episodes logged: ${input.episodes.count}`);
    if (input.episodes.avgDurationMin != null) lines.push(`  Avg duration: ${input.episodes.avgDurationMin} min`);
    if (input.episodes.byTimeOfDay) lines.push(`  Timing: ${input.episodes.byTimeOfDay}`);
    lines.push("");
  } else {
    lines.push("Episode Log");
    lines.push("  No episodes logged in this period.");
    lines.push("");
  }

  // Engagement
  lines.push("Engagement");
  lines.push(`  Protocols completed: ${input.protocolsCompleted}`);
  lines.push(`  Nila sessions: ${input.nilaSessions}`);
  if (input.featuresUsed.length > 0) {
    lines.push(`  Features used: ${input.featuresUsed.join(", ").replace(/_/g, " ")}`);
  }
  lines.push("");

  lines.push(SEPARATOR);
  lines.push(DISCLAIMER);

  return lines.join("\n");
}
