import { describe, it, expect } from "vitest";
import {
  buildCoverPage,
  buildExecutiveSummary,
  computeContentHash,
  validateIntegrity,
  type CoverPageData,
  type ExecutiveSummaryData,
} from "./clinicianCover";

describe("clinicianCover (Phase 20.8)", () => {
  describe("buildCoverPage", () => {
    const baseCover: CoverPageData = {
      coverId: "apple-rocket-ocean",
      periodLabel: "Month ending 2026-07-12",
      periodDays: 30,
      generationDate: "2026-07-12T14:30:00Z",
      sectionsIncluded: ["Check-ins", "Sleep", "Medications"],
      disclaimer: "Generated by NilaMind — not a clinical or diagnostic tool.",
    };

    it("returns a non-empty string with cover ID", () => {
      const cover = buildCoverPage(baseCover);
      expect(cover.length).toBeGreaterThan(50);
      expect(cover).toContain("apple-rocket-ocean");
    });

    it("includes period label and generation date", () => {
      const cover = buildCoverPage(baseCover);
      expect(cover).toContain("Month ending 2026-07-12");
      expect(cover).toContain("2026-07-12");
    });

    it("lists included sections", () => {
      const cover = buildCoverPage(baseCover);
      expect(cover).toContain("Check-ins");
      expect(cover).toContain("Sleep");
      expect(cover).toContain("Medications");
    });

    it("includes the disclaimer", () => {
      const cover = buildCoverPage(baseCover);
      expect(cover).toContain("not a clinical or diagnostic tool");
    });

    it("uses 'no identifier' when coverId is absent", () => {
      const cover = buildCoverPage({ ...baseCover, coverId: undefined });
      expect(cover).toContain("no identifier");
    });
  });

  describe("buildExecutiveSummary", () => {
    const baseSummary: ExecutiveSummaryData = {
      daysActive: 24,
      periodDays: 30,
      totalCheckins: 45,
      avgIntensity: 4.8,
      avgSleepHours: 7.2,
      currentPhase: "stable",
      activeMedications: 2,
      episodeCount: 3,
      distressDays: 5,
      prodromeDays: 2,
      currentStreak: 12,
    };

    it("returns a non-empty summary string", () => {
      const summary = buildExecutiveSummary(baseSummary);
      expect(summary.length).toBeGreaterThan(50);
    });

    it("includes key metrics", () => {
      const summary = buildExecutiveSummary(baseSummary);
      expect(summary).toContain("24/30");
      expect(summary).toContain("45");
      expect(summary).toContain("4.8");
    });

    it("includes phase marker", () => {
      const summary = buildExecutiveSummary(baseSummary);
      expect(summary).toContain("stable");
    });

    it("includes episode count", () => {
      const summary = buildExecutiveSummary(baseSummary);
      expect(summary).toContain("3");
    });
  });

  describe("computeContentHash", () => {
    it("returns a 64-character hex string (SHA-256)", () => {
      const hash = computeContentHash("test content");
      expect(hash).toMatch(/^[a-f0-9]{64}$/);
    });

    it("returns the same hash for the same input", () => {
      const h1 = computeContentHash("identical input");
      const h2 = computeContentHash("identical input");
      expect(h1).toBe(h2);
    });

    it("returns different hashes for different inputs", () => {
      const h1 = computeContentHash("content A");
      const h2 = computeContentHash("content B");
      expect(h1).not.toBe(h2);
    });
  });

  describe("validateIntegrity", () => {
    it("returns true when hash matches content", () => {
      const content = "report body here";
      const hash = computeContentHash(content);
      expect(validateIntegrity(content, hash)).toBe(true);
    });

    it("returns false when hash does not match content", () => {
      expect(validateIntegrity("content", "0000000000000000000000000000000000000000000000000000000000000000")).toBe(false);
    });

    it("returns false for malformed hash", () => {
      expect(validateIntegrity("content", "not-a-hash")).toBe(false);
    });
  });
});
