// Clinician-facing report — a structured summary a psychiatrist can read in 15 minutes.
// Privacy-first: generated on-device, user-initiated, never sent anywhere.
// Designed for PDF output via generatePdfBlob in exportReport.ts.

import type { EpisodeMarker } from "./episodeMarker";
import type { DiaryCardClinicianSummary } from "./diaryClinicianSummary";

const SEPARATOR = "-".repeat(40);
const DISCLAIMER = "Generated by NilaMind — not a clinical or diagnostic tool. For informational use only. This summary is a self-report aid for your conversation with a clinician, not a diagnosis or medical record.";

export interface AssessmentTrajectoryEntry {
  date: string; // YYYY-MM-DD
  total: number;
  severity: string; // e.g. "mild", "moderate"
}

export interface AssessmentTrajectory {
  instrument: string; // e.g. "PHQ-9", "GAD-7"
  entries: AssessmentTrajectoryEntry[];
}

export interface ClinicianMedication {
  name: string;
  dose: string;
  adherenceRate: number; // 0–100
  commonSideEffects: string[];
}

export interface ClinicianEpisodeEntry {
  date: string;
  time: string;
  dayOfWeek: string;
  timeOfDay: string;
  trigger: string | null;
  startIntensity: number;
  peakIntensity: number;
  endIntensity: number;
  durationMinutes: number;
  skillsHelpful: string[];
}

export interface ClinicianEpisodeSummary {
  count: number;
  byTimeOfDay: string; // e.g. "evening (2), afternoon (1)"
  avgDurationMin: number | null;
  entries: ClinicianEpisodeEntry[];
}

import type { ClinicianUsage } from "./clinicianPeriod";
import type { ClinicianPactForReport } from "./clinicianAggregations";
import type { ClinicianConnectionsForReport } from "./clinicianAggregations";

export interface ClinicianReportInput {
  periodLabel: string; // e.g. "Week ending 2026-07-12" or "Month ending 2026-07-12"
  periodDays: number; // 7, 30 or 90
  totalCheckins: number;
  daysActive: number;
  avgIntensity: number | null;
  avgSleepHours: number | null;
  circadianScore: number | null;
  socialRhythmVariability: number | null;
  assessmentTrajectories: AssessmentTrajectory[];
  medications: ClinicianMedication[];
  episodes: ClinicianEpisodeSummary;
  /** User-owner bipolar-phase markers (Phase 18) — self-logged, never a diagnosis. */
  phaseMarkers?: EpisodeMarker[];
  /** DBT diary card trends (urges/target behaviors, emotions, skills effectiveness). */
  diaryCardSummary?: DiaryCardClinicianSummary;
  /**
   * Phase 20.1 (B12): pact ("letter to my unwell self") status — exists / hasName / hasContact /
   * writtenAt / ratifiedAt / isStale. Never the letter text, the person's name, or contact.
   * Optional so legacy input fixtures (and any non-NilaMind callers) keep working.
   */
  pactState?: ClinicianPactForReport;
  /**
   * Phase 20.1 (B8): social connection log — how often, by what means, isolated/chronically isolated.
   * Privacy: raw dates/people never leave; only counts and type breakdown.
   */
  connections?: ClinicianConnectionsForReport;
  protocolsCompleted: number;
  nilaSessions: number;
  featuresUsed: string[];
  /** On-device usage + sleep signals for the window (no OS-level call logs — privacy promise). */
  usage?: ClinicianUsage;
  // Enhanced phenomenological summaries for better clinical insight
  emotionalStateSummary?: {
    intensityDistribution: { mild: number, moderate: number, severe: number };
    topGranularEmotions: Array<{ emotion: string, count: number }>;
    emotionalVariability: number;
  };
  contextualAnalysis?: {
    highIntensityContexts: Array<{ context: string, count: number }>;
    lowIntensityContexts: Array<{ context: string, count: number }>;
  };
  whatHelpedSummary?: Array<{ text: string, date: string }>;
  enhancedSleepDetails?: {
    avgBedtime: string | null;
    avgWakeTime: string | null;
    bedtimeConsistency: number;
    wakeTimeConsistency: number;
  };
  enhancedSocialRhythmDetails?: {
    anchorRegularity: Record<string, number>;
    averageAnchorTimes: Record<string, string>;
  };
  
  behavioralInsights?: {
    screenTimeCorrelation: number | null;
    socialMediaCorrelation: number | null;
    physicalActivityCorrelation: number | null;
    mobilityPatterns: {
      homeTimePercentage: number | null;
      locationVariety: number | null;
    };
  };
  
  userInsightsSummary?: {
    workingThrough: Array<{ text: string; date: string }>;
    patternsIdentified: Array<{ text: string; date: string }>;
    contextInsights: Array<{ text: string; date: string }>;
    valuesClarified: Array<{ text: string; date: string }>;
  };
}

function trendLabel(entries: AssessmentTrajectoryEntry[]): string | null {
  if (entries.length < 2) return null;
  const first = entries[0].total;
  const last = entries[entries.length - 1].total;
  const diff = first - last;
  if (Math.abs(diff) < 3) return "stable";
  return diff > 0 ? "improving" : "worsening";
}

export function buildClinicianReport(input: ClinicianReportInput): string {
  const lines: string[] = [];

  lines.push("NilaMind Clinician Summary");
  lines.push(input.periodLabel);
  lines.push(`  ${input.periodDays}-day report · generated from on-device data`);
  lines.push(SEPARATOR);
  lines.push("");

  // Check-ins
  lines.push("Check-ins");
  lines.push(`  Total: ${input.totalCheckins}`);
  lines.push(`  Active days: ${input.daysActive}/${input.periodDays}`);
  if (input.avgIntensity != null) {
    lines.push(`  Avg distress intensity: ${input.avgIntensity.toFixed(1)}/10`);
  }
  lines.push("");

  // Sleep & circadian
  if (input.avgSleepHours != null || input.circadianScore != null || input.socialRhythmVariability != null) {
    lines.push("Sleep & Circadian Rhythm");
    if (input.avgSleepHours != null) lines.push(`  Avg sleep: ${input.avgSleepHours.toFixed(1)}h`);
    if (input.circadianScore != null) lines.push(`  Sleep regularity score: ${input.circadianScore}/100 (higher = steadier)`);
    if (input.socialRhythmVariability != null) lines.push(`  Social rhythm variability: ±${input.socialRhythmVariability} min (lower = more regular)`);
    lines.push("");
  }

  // Assessment trajectories
  if (input.assessmentTrajectories.length > 0) {
    lines.push("Screening Trajectories (PHQ-9 / GAD-7)");
    for (const traj of input.assessmentTrajectories) {
      const trend = trendLabel(traj.entries);
      const vals = traj.entries.map((e) => `${e.date} = ${e.total} (${e.severity})`).join("; ");
      lines.push(`  ${traj.instrument}: ${vals}`);
      if (trend) lines.push(`    Trend: ${trend}`);
    }
    lines.push("  Note: PHQ-9 change >=5 points or GAD-7 change >=4 points is considered clinically meaningful.");
    lines.push("");
  } else {
    lines.push("Screening Trajectories");
    lines.push("  No assessments recorded in this period.");
    lines.push("");
  }

  // Medication adherence
  if (input.medications.length > 0) {
    lines.push("Medication Adherence");
    for (const med of input.medications) {
      const se = med.commonSideEffects.length > 0 ? ` · side effects: ${med.commonSideEffects.join(", ")}` : "";
      lines.push(`  ${med.name} ${med.dose} — ${med.adherenceRate}% adherence${se}`);
    }
    if (input.medications.length > 1) {
      const avg = Math.round(input.medications.reduce((s, m) => s + m.adherenceRate, 0) / input.medications.length);
      lines.push(`  Overall adherence: ${avg}%`);
    }
    lines.push("");
  } else {
    lines.push("Medication Adherence");
    lines.push("  No medications tracked in this period.");
    lines.push("");
  }

  // Episodes — F1/F2/F3/F6/F9: retrospective recall of episodes is unreliable (5-17%
  // sensitivity for extreme mood shifts); the value of this section is that entries were
  // captured close to the moment via the Episode Support debrief, not reconstructed later.
  // Do not collapse this back down to just count/avg/timing — that discards the one advantage
  // this data has over the patient trying to recall it in the room.
  if (input.episodes.count > 0) {
    lines.push("Episode Log");
    lines.push(`  Episodes logged: ${input.episodes.count}`);
    if (input.episodes.avgDurationMin != null) lines.push(`  Avg duration: ${input.episodes.avgDurationMin} min`);
    if (input.episodes.byTimeOfDay) lines.push(`  Timing: ${input.episodes.byTimeOfDay}`);
    const entries = input.episodes.entries;
    if (entries.length > 0) {
      lines.push("");
      const shown = entries.slice(0, 8);
      for (const e of shown) {
        const triggerText = e.trigger && e.trigger !== "Skipped" ? `trigger: "${e.trigger}"` : "trigger not recorded";
        const helpedText = e.skillsHelpful.length > 0 ? ` · helped: ${e.skillsHelpful.join(", ")}` : "";
        lines.push(`  ${e.date} (${e.dayOfWeek}) ${e.time} — ${triggerText} · intensity ${e.startIntensity} → ${e.peakIntensity} → ${e.endIntensity} over ${e.durationMinutes} min${helpedText}`);
      }
      if (entries.length > 8) {
        lines.push(`  (showing most recent 8 of ${entries.length})`);
      }
    }
    lines.push("");
  } else {
    lines.push("Episode Log");
    lines.push("  No episodes logged in this period.");
    lines.push("");
  }

  // Bipolar phase markers (Phase 18 — self-logged, user-owned)
  if (input.phaseMarkers && input.phaseMarkers.length > 0) {
    lines.push("Bipolar Phase Markers (self-logged)");
    for (const m of input.phaseMarkers) {
      const range = m.startDate === m.endDate ? m.startDate : `${m.startDate} – ${m.endDate}`;
      const note = m.note ? ` (${m.note})` : "";
      lines.push(`  ${range}: ${m.phase.charAt(0).toUpperCase() + m.phase.slice(1)}${note}`);
    }
    lines.push("  Note: self-reported phase tags, for context only — not a clinical diagnosis.");
    lines.push("");
  }

  // DBT Diary Card Summary
  if (input.diaryCardSummary) {
    const d = input.diaryCardSummary;
    lines.push("DBT Diary Card Summary");
    lines.push(`  Days logged: ${d.daysLogged}/${d.periodDays}`);

    if (d.urges.length > 0) {
      lines.push("  Target behavior urges (0-5 scale):");
      for (const u of d.urges) {
        const days = u.daysActedOn === 1 ? "1 day" : `${u.daysActedOn} days`;
        lines.push(`    ${u.label}: avg ${u.avgIntensity.toFixed(1)}, peak ${u.peakIntensity} — acted on ${days}`);
      }
    }

    const emotionEntries = Object.entries(d.emotionAverages);
    if (emotionEntries.length > 0) {
      const summary = emotionEntries
        .map(([emotion, avg]) => {
          const label = emotion.charAt(0).toUpperCase() + emotion.slice(1);
          const peak = d.emotionPeaks[emotion];
          return `${label} ${avg.toFixed(1)}${peak != null ? ` (peak ${peak})` : ""}`;
        })
        .join(" · ");
      lines.push(`  Emotion averages (0-5): ${summary}`);
    }

    if (d.skills.length > 0) {
      const skillsLine = d.skills
        .map((s) => `${s.skill} (used ${s.timesUsed}×, helped ${s.timesHelped}×, no help ${s.timesNoHelp}×)`)
        .join(" · ");
      lines.push(`  Skills: ${skillsLine}`);
    }

    if (d.notableDays.length > 0) {
      lines.push("  Notable days:");
      for (const nd of d.notableDays) {
        lines.push(`    ${nd.date}: ${nd.reason}`);
      }
    }

    lines.push("  Note: self-reported via structured DBT-style daily card; 0=none, 5=extreme/highly effective.");
    lines.push("");
  }

  // Phase 20.1 (B12) — Support Arrangement (pact). The patient, when well, named a trusted person and
  // wrote themselves a letter for future unwell moments. The clinician benefits from knowing whether
  // such an arrangement exists and whether it is fresh. Privacy: this block must never include the
  // letter body, the trusted person's name, or their contact; only metadata the patient consents to
  // by having stored the pact at all. Tested by privacy-guard tests in clinicianAggregations.test.ts
  // AND the render-no-PII test in clinicianReport.test.ts.
  if (input.pactState) {
    const p = input.pactState;
    lines.push("Support Arrangement (pact, self-authored)");
    if (!p.exists) {
      lines.push("  No pact on file in this period.");
    } else {
      lines.push("  Pact on file: yes");
      lines.push(`  Trusted-person name recorded: ${p.hasName ? "yes" : "no"}`);
      lines.push(`  Contact recorded: ${p.hasContact ? "yes" : "no"}`);
      lines.push(`  Originally written (well-self): ${p.writtenAt ?? "—"}`);
      lines.push(`  Last re-confirmed: ${p.ratifiedAt ?? "—"}`);
      lines.push(`  Stale re-confirmation (>90d): ${p.isStale ? "yes — well-self should re-confirm" : "no"}`);
    }
    lines.push("  Note: self-authored support arrangement for context only — not a clinical directive.");
    lines.push("");
  }

  // Phase 20.1 (B8) — Social connection summary. Research: Social isolation is a documented
  // depression/bipolar relapse risk factor (Sylvies 2019; IPSRT). The clinician benefits from
  // understanding HOW connected the patient is (not who they connected with). Privacy: the block
  // never exposes specific people, dates, or locations — only weekly counts and connection types.
  if (input.connections) {
    const c = input.connections;
    lines.push("Social Connection");
    if (!c.hasData) {
      lines.push("  No connection logs in this period.");
    } else {
      lines.push(`  Total logged connections: ${c.totalConnections}`);
      const typeLines = Object.entries(c.byType)
        .map(([type, n]) => `${type.replace(/_/g, " ")}: ${n}`)
        .join(", ");
      lines.push(`  By type: ${typeLines}`);
      lines.push(`  Recent (last 7 days): ${c.lastWeekCount} connection${c.lastWeekCount !== 1 ? "s" : ""} — ${c.recentLevel}`);
      if (c.persistentlyLow) {
        lines.push("  Pattern: chronically low social contact across this period");
      }
      if (c.weeklyCounts.length > 0) {
        lines.push(`  Weeks with activity: ${c.weeklyCounts.length}`);
      }
    }
    lines.push("");
  }

  // Engagement
  lines.push("Engagement");
  lines.push(`  Protocols completed: ${input.protocolsCompleted}`);
  lines.push(`  Nila sessions: ${input.nilaSessions}`);
  if (input.featuresUsed.length > 0) {
    lines.push(`  Features used: ${input.featuresUsed.join(", ").replace(/_/g, " ")}`);
  }
  lines.push("");

  // App & conversation usage (on-device only — no OS-level call/app logs)
  if (input.usage) {
    const u = input.usage;
    lines.push("App & Conversation Usage (on-device)");
    lines.push(`  Active check-in days: ${u.daysActive}/${u.periodDays}`);
    lines.push(`  App-open days: ${u.appOpenDays}/${u.periodDays}`);
    lines.push(`  Nila conversation turns: ${u.nilaTurns}`);
    if (u.avgSleepHours != null) {
      lines.push(`  Avg sleep (from check-ins): ${u.avgSleepHours.toFixed(1)}h`);
    }
    lines.push(`  Features used: ${u.featuresUsed.length > 0 ? u.featuresUsed.join(", ").replace(/_/g, " ") : "none"}`);
    if (u.retention) {
      const r = u.retention;
      lines.push(`  Consistency: ${r.totalActiveDays} active day(s), current streak ${r.currentStreak}`);
      lines.push(`  Retention: Day-7 still active — ${r.day7Active ? "yes" : "no"}; Day-30 still active — ${r.day30Active ? "yes" : "no"}`);
    }
    lines.push("");
  }

    // Enhanced Phenomenological Summary (if available)
    if (input.emotionalStateSummary || input.contextualAnalysis || input.whatHelpedSummary || 
        input.enhancedSleepDetails || input.enhancedSocialRhythmDetails) {
      lines.push("Enhanced Phenomenological Summary");
      
      if (input.emotionalStateSummary) {
        const ess = input.emotionalStateSummary;
        lines.push("  Emotional State Distribution:");
        lines.push(`    • Mild distress (1-3): ${ess.intensityDistribution.mild}%`);
        lines.push(`    • Moderate distress (4-6): ${ess.intensityDistribution.moderate}%`);
        lines.push(`    • Severe distress (7-10): ${ess.intensityDistribution.severe}%`);
        lines.push(`    • Emotional variability (SD): ${ess.emotionalVariability}`);
        if (ess.topGranularEmotions.length > 0) {
          lines.push("  Top emotional experiences:");
          ess.topGranularEmotions.forEach((emo, idx) => {
            if (idx < 3) { // Show top 3
              lines.push(`    • ${emo.emotion}: ${emo.count} occurrences`);
            }
          });
        }
        lines.push("");
      }
      
      if (input.contextualAnalysis) {
        const ca = input.contextualAnalysis;
        lines.push("  Contextual Associations:");
        if (ca.highIntensityContexts.length > 0) {
          lines.push("    High distress contexts:");
          ca.highIntensityContexts.forEach((ctx, idx) => {
            if (idx < 3) { // Show top 3
              lines.push(`      • ${ctx.context}: ${ctx.count} times`);
            }
          });
        }
        if (ca.lowIntensityContexts.length > 0) {
          lines.push("    Lower distress contexts:");
          ca.lowIntensityContexts.forEach((ctx, idx) => {
            if (idx < 3) { // Show top 3
              lines.push(`      • ${ctx.context}: ${ctx.count} times`);
            }
          });
        }
        lines.push("");
      }
      
      if (input.whatHelpedSummary && input.whatHelpedSummary.length > 0) {
        lines.push("  What has helped (recent insights):");
        input.whatHelpedSummary.slice(0, 3).forEach((item, idx) => {
          lines.push(`    • ${item.text} (${item.date})`);
        });
        lines.push("");
      }
      
      if (input.enhancedSleepDetails) {
        const esd = input.enhancedSleepDetails;
        lines.push("  Sleep Pattern Analysis:");
        if (esd.avgBedtime) {
          lines.push(`    • Average bedtime: ${esd.avgBedtime}`);
        }
        if (esd.avgWakeTime) {
          lines.push(`    • Average wake time: ${esd.avgWakeTime}`);
        }
        if (esd.bedtimeConsistency > 0) {
          lines.push(`    • Bedtime consistency: ${(esd.bedtimeConsistency * 100).toFixed(0)}%`);
        }
        if (esd.wakeTimeConsistency > 0) {
          lines.push(`    • Wake time consistency: ${(esd.wakeTimeConsistency * 100).toFixed(0)}%`);
        }
        lines.push("");
      }
      
if (input.enhancedSocialRhythmDetails) {
         const esrd = input.enhancedSocialRhythmDetails;
         lines.push("  Social Rhythm Regularity:");
         Object.entries(esrd.anchorRegularity).forEach(([anchor, regularity]) => {
           const avgTime = esrd.averageAnchorTimes[anchor] || "N/A";
           lines.push(`    • ${anchor}: ${(regularity * 100).toFixed(0)}% regular (avg: ${avgTime})`);
         });
         lines.push("");
       }
       
       if (input.behavioralInsights) {
         const bi = input.behavioralInsights;
         lines.push("  Behavioral Insights:");
         if (bi.screenTimeCorrelation !== null) {
           const direction = bi.screenTimeCorrelation > 0 ? "positive" : bi.screenTimeCorrelation < 0 ? "negative" : "no";
           lines.push(`    • Screen time vs mood correlation: ${(bi.screenTimeCorrelation * 100).toFixed(0)}% (${direction})`);
         }
         if (bi.socialMediaCorrelation !== null) {
           const direction = bi.socialMediaCorrelation > 0 ? "positive" : bi.socialMediaCorrelation < 0 ? "negative" : "no";
           lines.push(`    • Social media use vs mood correlation: ${(bi.socialMediaCorrelation * 100).toFixed(0)}% (${direction})`);
         }
         if (bi.physicalActivityCorrelation !== null) {
           const direction = bi.physicalActivityCorrelation > 0 ? "positive" : bi.physicalActivityCorrelation < 0 ? "negative" : "no";
           lines.push(`    • Physical activity vs mood correlation: ${(bi.physicalActivityCorrelation * 100).toFixed(0)}% (${direction})`);
         }
         if (bi.mobilityPatterns) {
           const mp = bi.mobilityPatterns;
           if (mp.homeTimePercentage !== null) {
             lines.push(`    • Estimated time at home: ${(mp.homeTimePercentage * 100).toFixed(0)}%`);
           }
           if (mp.locationVariety !== null) {
             lines.push(`    • Location variety score: ${mp.locationVariety.toFixed(1)} unique areas`);
           }
         }
         lines.push("");
       }
       
       if (input.userInsightsSummary) {
         const uis = input.userInsightsSummary;
         lines.push("  User Insights Summary:");
         
         if (uis.workingThrough.length > 0) {
           lines.push("    Working Through:");
           uis.workingThrough.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         if (uis.patternsIdentified.length > 0) {
           lines.push("    Patterns Identified:");
           uis.patternsIdentified.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         if (uis.contextInsights.length > 0) {
           lines.push("    Context Insights:");
           uis.contextInsights.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         if (uis.valuesClarified.length > 0) {
           lines.push("    Values Clarified:");
           uis.valuesClarified.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         lines.push("");
       }
    }
    
    lines.push(SEPARATOR);
    lines.push(DISCLAIMER);
    
    return lines.join("\n");
}
