// Clinician-facing report — a structured summary a psychiatrist can read in 15 minutes.
// Privacy-first: generated on-device, user-initiated, never sent anywhere.
// Designed for PDF output via generatePdfBlob in exportReport.ts.

import type { CrisisMetrics } from "./crisisSafetyValidation";
import type { RiskAssessment } from "./temporalRiskAssessment";

const SEPARATOR = "-".repeat(40);
const DISCLAIMER = "Generated by NilaMind — not a clinical or diagnostic tool. For informational use only. This summary is a self-report aid for your conversation with a clinician, not a diagnosis or medical record.";

export interface AssessmentTrajectoryEntry {
  date: string; // YYYY-MM-DD
  total: number;
  severity: string; // e.g. "mild", "moderate"
}

export interface AssessmentTrajectory {
  instrument: string; // e.g. "PHQ-9", "GAD-7"
  entries: AssessmentTrajectoryEntry[];
}

export interface ClinicianMedication {
  name: string;
  dose: string;
  adherenceRate: number; // 0–100
  commonSideEffects: string[];
}

export interface ClinicianEpisodeSummary {
  count: number;
  byTimeOfDay: string; // e.g. "evening (2), afternoon (1)"
  avgDurationMin: number | null;
}

export interface ClinicianReportInput {
  periodLabel: string; // e.g. "Week ending 2026-07-12" or "Month ending 2026-07-12"
  periodDays: number; // 7 or 30
  totalCheckins: number;
  daysActive: number;
  avgIntensity: number | null;
  avgSleepHours: number | null;
  circadianScore: number | null;
  socialRhythmVariability: number | null;
  assessmentTrajectories: AssessmentTrajectory[];
  medications: ClinicianMedication[];
  episodes: ClinicianEpisodeSummary;
  protocolsCompleted: number;
  nilaSessions: number;
  featuresUsed: string[];
  crisisMetrics?: CrisisMetrics; // Optional crisis detection performance metrics
  temporalRiskAssessment?: RiskAssessment; // Optional temporal risk assessment
  // Enhanced phenomenological summaries for better clinical insight
  emotionalStateSummary?: {
    intensityDistribution: { mild: number, moderate: number, severe: number };
    topGranularEmotions: Array<{ emotion: string, count: number }>;
    emotionalVariability: number;
  };
  contextualAnalysis?: {
    highIntensityContexts: Array<{ context: string, count: number }>;
    lowIntensityContexts: Array<{ context: string, count: number }>;
  };
  whatHelpedSummary?: Array<{ text: string, date: string }>;
  enhancedSleepDetails?: {
    avgBedtime: string | null;
    avgWakeTime: string | null;
    bedtimeConsistency: number;
    wakeTimeConsistency: number;
  };
  enhancedSocialRhythmDetails?: {
    anchorRegularity: Record<string, number>;
    averageAnchorTimes: Record<string, string>;
  };
  
  behavioralInsights?: {
    screenTimeCorrelation: number | null;
    socialMediaCorrelation: number | null;
    physicalActivityCorrelation: number | null;
    mobilityPatterns: {
      homeTimePercentage: number | null;
      locationVariety: number | null;
    };
  };
  
  userInsightsSummary?: {
    workingThrough: Array<{ text: string; date: string }>;
    patternsIdentified: Array<{ text: string; date: string }>;
    contextInsights: Array<{ text: string; date: string }>;
    valuesClarified: Array<{ text: string; date: string }>;
  };
}

function trendLabel(entries: AssessmentTrajectoryEntry[]): string | null {
  if (entries.length < 2) return null;
  const first = entries[0].total;
  const last = entries[entries.length - 1].total;
  const diff = first - last;
  if (Math.abs(diff) < 3) return "stable";
  return diff > 0 ? "improving" : "worsening";
}

export function buildClinicianReport(input: ClinicianReportInput): string {
  const lines: string[] = [];

  lines.push("NilaMind Clinician Summary");
  lines.push(input.periodLabel);
  lines.push(`  ${input.periodDays}-day report · generated from on-device data`);
  lines.push(SEPARATOR);
  lines.push("");

  // Check-ins
  lines.push("Check-ins");
  lines.push(`  Total: ${input.totalCheckins}`);
  lines.push(`  Active days: ${input.daysActive}/${input.periodDays}`);
  if (input.avgIntensity != null) {
    lines.push(`  Avg distress intensity: ${input.avgIntensity.toFixed(1)}/10`);
  }
  lines.push("");

  // Sleep & circadian
  if (input.avgSleepHours != null || input.circadianScore != null || input.socialRhythmVariability != null) {
    lines.push("Sleep & Circadian Rhythm");
    if (input.avgSleepHours != null) lines.push(`  Avg sleep: ${input.avgSleepHours.toFixed(1)}h`);
    if (input.circadianScore != null) lines.push(`  Sleep regularity score: ${input.circadianScore}/100 (higher = steadier)`);
    if (input.socialRhythmVariability != null) lines.push(`  Social rhythm variability: ±${input.socialRhythmVariability} min (lower = more regular)`);
    lines.push("");
  }

  // Assessment trajectories
  if (input.assessmentTrajectories.length > 0) {
    lines.push("Screening Trajectories (PHQ-9 / GAD-7)");
    for (const traj of input.assessmentTrajectories) {
      const trend = trendLabel(traj.entries);
      const vals = traj.entries.map((e) => `${e.date} = ${e.total} (${e.severity})`).join("; ");
      lines.push(`  ${traj.instrument}: ${vals}`);
      if (trend) lines.push(`    Trend: ${trend}`);
    }
    lines.push("  Note: PHQ-9 change >=5 points or GAD-7 change >=4 points is considered clinically meaningful.");
    lines.push("");
  } else {
    lines.push("Screening Trajectories");
    lines.push("  No assessments recorded in this period.");
    lines.push("");
  }

  // Medication adherence
  if (input.medications.length > 0) {
    lines.push("Medication Adherence");
    for (const med of input.medications) {
      const se = med.commonSideEffects.length > 0 ? ` · side effects: ${med.commonSideEffects.join(", ")}` : "";
      lines.push(`  ${med.name} ${med.dose} — ${med.adherenceRate}% adherence${se}`);
    }
    if (input.medications.length > 1) {
      const avg = Math.round(input.medications.reduce((s, m) => s + m.adherenceRate, 0) / input.medications.length);
      lines.push(`  Overall adherence: ${avg}%`);
    }
    lines.push("");
  } else {
    lines.push("Medication Adherence");
    lines.push("  No medications tracked in this period.");
    lines.push("");
  }

  // Episodes
  if (input.episodes.count > 0) {
    lines.push("Episode Log");
    lines.push(`  Episodes logged: ${input.episodes.count}`);
    if (input.episodes.avgDurationMin != null) lines.push(`  Avg duration: ${input.episodes.avgDurationMin} min`);
    if (input.episodes.byTimeOfDay) lines.push(`  Timing: ${input.episodes.byTimeOfDay}`);
    lines.push("");
  } else {
    lines.push("Episode Log");
    lines.push("  No episodes logged in this period.");
    lines.push("");
  }

  // Engagement
  lines.push("Engagement");
  lines.push(`  Protocols completed: ${input.protocolsCompleted}`);
  lines.push(`  Nila sessions: ${input.nilaSessions}`);
  if (input.featuresUsed.length > 0) {
    lines.push(`  Features used: ${input.featuresUsed.join(", ").replace(/_/g, " ")}`);
  }
  lines.push("");

// Crisis Detection Performance (if available)
   if (input.crisisMetrics) {
     const m = input.crisisMetrics;
     lines.push("Crisis Detection Performance");
     if (m.totalEvaluations > 0) {
       lines.push(`  Evaluations: ${m.totalEvaluations}`);
       lines.push(`  Sensitivity (Recall): ${(m.sensitivity! * 100).toFixed(1)}%`);
       lines.push(`  Specificity: ${(m.specificity! * 100).toFixed(1)}%`);
       lines.push(`  PPV (Precision): ${(m.ppv! * 100).toFixed(1)}%`);
       lines.push(`  NPV: ${(m.npv! * 100).toFixed(1)}%`);
       lines.push(`  F1 Score: ${m.f1!.toFixed(3)}`);
       lines.push(`  Accuracy: ${(m.accuracy! * 100).toFixed(1)}%`);
       
       // Add calibration info if available
       if (m.expectedCalibrationError !== undefined) {
         lines.push(`  Expected Calibration Error: ${(m.expectedCalibrationError * 100).toFixed(1)}%`);
       }
       
       // Add clinical interpretation
       lines.push("");
       lines.push(`  Clinical Interpretation:`);
       if (m.sensitivity! >= 0.8) {
         lines.push(`    • Good sensitivity: captures most genuine crisis signals`);
       } else if (m.sensitivity! >= 0.6) {
         lines.push(`    • Moderate sensitivity: may miss some crisis signals`);
       } else {
         lines.push(`    • Lower sensitivity: may miss crisis signals - consider clinical interview`);
       }
       
       if (m.specificity! >= 0.8) {
         lines.push(`    • Good specificity: few false alarms`);
       } else if (m.specificity! >= 0.6) {
         lines.push(`    • Moderate specificity: some false alerts possible`);
       } else {
         lines.push(`    • Lower sensitivity: more frequent alerts - review with clinical judgment`);
       }
     } else {
       lines.push("  No crisis evaluation data available for this period.");
       lines.push("  Crisis detection performance metrics require evaluated interactions.");
     }
     lines.push("");
   }
   
// Temporal Risk Assessment (if available)
    if (input.temporalRiskAssessment) {
      const trauma = input.temporalRiskAssessment;
      lines.push("Temporal Risk Assessment");
      lines.push(`  Overall Risk Level: ${trauma.riskLevel.toUpperCase()}`);
      lines.push(`  Risk Score: ${(trauma.riskScore * 100).toFixed(1)} / 100`);
      lines.push(`  Assessment Confidence: ${(trauma.confidence * 100).toFixed(0)}%`);
      lines.push(`  Trend: ${trauma.trend.toUpperCase()}`);
      lines.push(`  Evaluation Period: ${trauma.windowDays}-day lookback`);
      
      lines.push("");
      lines.push(`  Risk Factors:`);
      lines.push(`    • Sleep Deprivation: ${(trauma.factors.sleepDeprivation * 100).toFixed(0)}%`);
      lines.push(`    • Sleep Variability: ${(trauma.factors.sleepVariability * 100).toFixed(0)}%`);
      lines.push(`    • Rhythm Irregularity: ${(trauma.factors.rhythmIrregularity * 100).toFixed(0)}%`);
      lines.push(`    • Mood Deterioration: ${(trauma.factors.moodDeterioration * 100).toFixed(0)}%`);
      lines.push(`    • Affective Lability: ${(trauma.factors.affectiveLability * 100).toFixed(0)}%`);
      lines.push(`    • Social Withdrawal: ${(trauma.factors.socialWithdrawal * 100).toFixed(0)}%`);
      lines.push(`    • Depression Severity: ${(trauma.factors.depressionSeverity * 100).toFixed(0)}%`);
      lines.push(`    • Anxiety Severity: ${(trauma.factors.anxietySeverity * 100).toFixed(0)}%`);
      lines.push(`    • Suicidal Ideation: ${(trauma.factors.suicidalIdeation * 100).toFixed(0)}%`);
      
      lines.push("");
      lines.push(`  Clinical Interpretation:`);
      switch (trauma.riskLevel) {
        case 'low':
          lines.push(`    • Low risk: Continue routine monitoring and self-care practices`);
          break;
        case 'moderate':
          lines.push(`    • Moderate risk: Consider increasing self-monitoring and support`);
          break;
        case 'high':
          lines.push(`    • High risk: Consider contacting mental health professional or trusted support`);
          break;
        case 'imminent':
          lines.push(`    • Elevated risk: Strongly consider reaching out for immediate support`);
          lines.push(`    • If experiencing crisis thoughts, use crisis resources or contact emergency services`);
          break;
      }
      
      if (trauma.recommendations.length > 0) {
        lines.push("");
        lines.push(`  Recommendations:`);
        trauma.recommendations.forEach((rec, idx) => {
          lines.push(`    • ${rec}`);
        });
      }
      
      lines.push("");
    }
    
    // Enhanced Phenomenological Summary (if available)
    if (input.emotionalStateSummary || input.contextualAnalysis || input.whatHelpedSummary || 
        input.enhancedSleepDetails || input.enhancedSocialRhythmDetails) {
      lines.push("Enhanced Phenomenological Summary");
      
      if (input.emotionalStateSummary) {
        const ess = input.emotionalStateSummary;
        lines.push("  Emotional State Distribution:");
        lines.push(`    • Mild distress (1-3): ${ess.intensityDistribution.mild}%`);
        lines.push(`    • Moderate distress (4-6): ${ess.intensityDistribution.moderate}%`);
        lines.push(`    • Severe distress (7-10): ${ess.intensityDistribution.severe}%`);
        lines.push(`    • Emotional variability (SD): ${ess.emotionalVariability}`);
        if (ess.topGranularEmotions.length > 0) {
          lines.push("  Top emotional experiences:");
          ess.topGranularEmotions.forEach((emo, idx) => {
            if (idx < 3) { // Show top 3
              lines.push(`    • ${emo.emotion}: ${emo.count} occurrences`);
            }
          });
        }
        lines.push("");
      }
      
      if (input.contextualAnalysis) {
        const ca = input.contextualAnalysis;
        lines.push("  Contextual Associations:");
        if (ca.highIntensityContexts.length > 0) {
          lines.push("    High distress contexts:");
          ca.highIntensityContexts.forEach((ctx, idx) => {
            if (idx < 3) { // Show top 3
              lines.push(`      • ${ctx.context}: ${ctx.count} times`);
            }
          });
        }
        if (ca.lowIntensityContexts.length > 0) {
          lines.push("    Lower distress contexts:");
          ca.lowIntensityContexts.forEach((ctx, idx) => {
            if (idx < 3) { // Show top 3
              lines.push(`      • ${ctx.context}: ${ctx.count} times`);
            }
          });
        }
        lines.push("");
      }
      
      if (input.whatHelpedSummary && input.whatHelpedSummary.length > 0) {
        lines.push("  What has helped (recent insights):");
        input.whatHelpedSummary.slice(0, 3).forEach((item, idx) => {
          lines.push(`    • ${item.text} (${item.date})`);
        });
        lines.push("");
      }
      
      if (input.enhancedSleepDetails) {
        const esd = input.enhancedSleepDetails;
        lines.push("  Sleep Pattern Analysis:");
        if (esd.avgBedtime) {
          lines.push(`    • Average bedtime: ${esd.avgBedtime}`);
        }
        if (esd.avgWakeTime) {
          lines.push(`    • Average wake time: ${esd.avgWakeTime}`);
        }
        if (esd.bedtimeConsistency > 0) {
          lines.push(`    • Bedtime consistency: ${(esd.bedtimeConsistency * 100).toFixed(0)}%`);
        }
        if (esd.wakeTimeConsistency > 0) {
          lines.push(`    • Wake time consistency: ${(esd.wakeTimeConsistency * 100).toFixed(0)}%`);
        }
        lines.push("");
      }
      
if (input.enhancedSocialRhythmDetails) {
         const esrd = input.enhancedSocialRhythmDetails;
         lines.push("  Social Rhythm Regularity:");
         Object.entries(esrd.anchorRegularity).forEach(([anchor, regularity]) => {
           const avgTime = esrd.averageAnchorTimes[anchor] || "N/A";
           lines.push(`    • ${anchor}: ${(regularity * 100).toFixed(0)}% regular (avg: ${avgTime})`);
         });
         lines.push("");
       }
       
       if (input.behavioralInsights) {
         const bi = input.behavioralInsights;
         lines.push("  Behavioral Insights:");
         if (bi.screenTimeCorrelation !== null) {
           const direction = bi.screenTimeCorrelation > 0 ? "positive" : bi.screenTimeCorrelation < 0 ? "negative" : "no";
           lines.push(`    • Screen time vs mood correlation: ${(bi.screenTimeCorrelation * 100).toFixed(0)}% (${direction})`);
         }
         if (bi.socialMediaCorrelation !== null) {
           const direction = bi.socialMediaCorrelation > 0 ? "positive" : bi.socialMediaCorrelation < 0 ? "negative" : "no";
           lines.push(`    • Social media use vs mood correlation: ${(bi.socialMediaCorrelation * 100).toFixed(0)}% (${direction})`);
         }
         if (bi.physicalActivityCorrelation !== null) {
           const direction = bi.physicalActivityCorrelation > 0 ? "positive" : bi.physicalActivityCorrelation < 0 ? "negative" : "no";
           lines.push(`    • Physical activity vs mood correlation: ${(bi.physicalActivityCorrelation * 100).toFixed(0)}% (${direction})`);
         }
         if (bi.mobilityPatterns) {
           const mp = bi.mobilityPatterns;
           if (mp.homeTimePercentage !== null) {
             lines.push(`    • Estimated time at home: ${(mp.homeTimePercentage * 100).toFixed(0)}%`);
           }
           if (mp.locationVariety !== null) {
             lines.push(`    • Location variety score: ${mp.locationVariety.toFixed(1)} unique areas`);
           }
         }
         lines.push("");
       }
       
       if (input.userInsightsSummary) {
         const uis = input.userInsightsSummary;
         lines.push("  User Insights Summary:");
         
         if (uis.workingThrough.length > 0) {
           lines.push("    Working Through:");
           uis.workingThrough.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         if (uis.patternsIdentified.length > 0) {
           lines.push("    Patterns Identified:");
           uis.patternsIdentified.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         if (uis.contextInsights.length > 0) {
           lines.push("    Context Insights:");
           uis.contextInsights.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         if (uis.valuesClarified.length > 0) {
           lines.push("    Values Clarified:");
           uis.valuesClarified.slice(0, 3).forEach((insight, idx) => {
             lines.push(`      • ${insight.text} (${insight.date})`);
           });
         }
         
         lines.push("");
       }
    }
    
    lines.push(SEPARATOR);
    lines.push(DISCLAIMER);
    
    return lines.join("\n");
}
