// Phase 7 — Clinician-friendly export (PDF + CSV).
// Privacy-first: user-initiated, saved to device only, never sent anywhere.
// Core functions are pure (data in, data out) for testability.

import { jsPDF } from "jspdf";
import { Capacitor } from "@capacitor/core";
import { Filesystem, Directory, Encoding } from "@capacitor/filesystem";
import type { CheckInEntry } from "../types";
import type { RetentionSummary } from "./retentionMetrics";
import type { PilotSummary } from "./pilotStudy";
import type { AssessmentEntry } from "./assessments";
import type { FeedbackSummary } from "./nilaFeedback";

const DISCLAIMER = "Generated by NilaMind — not a clinical or diagnostic tool. For informational use only.";
const CSV_HEADER = "Date,Emotion,Intensity (1-10),Sleep Hours,Context,Granular Emotion";

function escapeCsv(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

/** Build a CSV string from check-in data. Returns header + rows, or empty string when no data. */
export function generateCsvReport(checkins: CheckInEntry[]): string {
  if (!checkins || checkins.length === 0) return "";
  const rows = checkins.map((e) => {
    const date = escapeCsv(e.date ?? "");
    const emotion = escapeCsv((e.emotion ?? "").replace(/ \(Nila\)$/, ""));
    const intensity = e.intensity ?? "";
    const sleepHours = e.sleepHours != null ? String(e.sleepHours) : "";
    const context = escapeCsv(e.context ?? "");
    const granular = escapeCsv(e.granularEmotion ?? "");
    return `${date},${emotion},${intensity},${sleepHours},${context},${granular}`;
  });
  return `${CSV_HEADER}\n${rows.join("\n")}\n\n${DISCLAIMER}`;
}

const yesNo = (b: boolean) => (b ? "yes" : "no");

/** Build a plain-text summary report. `retention`/`pilot`/`assessments`/`feedback` are optional so existing callers/tests are unaffected. */
export function buildTextReport(
  checkins: CheckInEntry[],
  assessmentCount?: number,
  retention?: RetentionSummary,
  pilot?: PilotSummary,
  assessments?: AssessmentEntry[],
  feedback?: FeedbackSummary,
): string {
  const lines: string[] = [];
  lines.push("NilaMind Wellness Report");
  lines.push("=".repeat(40));
  lines.push("");

  if (checkins.length > 0) {
    const valid = checkins.filter((c) => typeof c.intensity === "number");
    const avg = valid.length > 0
      ? (valid.reduce((s, c) => s + c.intensity, 0) / valid.length).toFixed(1)
      : "—";
    lines.push(`Total check-ins logged: ${checkins.length}`);
    lines.push(`Average distress intensity: ${avg}/10`);
    const withSleep = valid.filter((c) => typeof c.sleepHours === "number" && c.sleepHours > 0);
    if (withSleep.length > 0) {
      const avgSleep = (withSleep.reduce((s, c) => s + (c.sleepHours ?? 0), 0) / withSleep.length).toFixed(1);
      lines.push(`Average sleep: ${avgSleep}h (${withSleep.length} nights)`);
    }
  } else {
    lines.push("No check-ins recorded yet.");
  }

  const asmts = assessments ?? [];
  const asmtCount = assessments ? asmts.length : (assessmentCount ?? 0);
  if (asmtCount > 0) {
    lines.push("");
    lines.push(`Screenings completed: ${asmtCount}`);
  }
  if (asmts.length > 0) {
    lines.push("");
    lines.push("Assessments over time (oldest to newest):");
    const byInstrument = new Map<string, AssessmentEntry[]>();
    for (const a of asmts) {
      const arr = byInstrument.get(a.instrument) ?? [];
      arr.push(a);
      byInstrument.set(a.instrument, arr);
    }
    for (const [inst, entries] of byInstrument) {
      const sorted = entries
        .slice()
        .sort((a, b) => a.date.localeCompare(b.date) || a.timestamp.localeCompare(b.timestamp))
        .slice(-10); // bound the output to the 10 most recent per instrument
      lines.push(`${inst}: ${sorted.map((e) => `${e.date} = ${e.total} (${e.severity})`).join("; ")}`);
    }
  }

  if (retention && retention.totalActiveDays > 0) {
    lines.push("");
    lines.push("Retention & engagement (from your own app-open history, computed on-device)");
    lines.push(`First used: ${retention.firstUseDay} (${retention.daysSinceFirstUse} days ago)`);
    lines.push(`Days you opened NilaMind: ${retention.totalActiveDays}`);
    lines.push(`Active days in the last 7 / 30: ${retention.activeDaysLast7} / ${retention.activeDaysLast30}`);
    if (retention.lastOpenDay) {
      lines.push(`Last opened: ${retention.lastOpenDay} (${retention.currentGapDays} days ago)`);
    }
    lines.push(`Longest gap between opens: ${retention.longestGapDays} days`);
    lines.push(
      `Still opening after 1 / 7 / 14 / 30 days: ${yesNo(retention.retainedDay1)} / ` +
      `${yesNo(retention.retainedDay7)} / ${yesNo(retention.retainedDay14)} / ${yesNo(retention.retainedDay30)}`,
    );
  }

  if (pilot) {
    lines.push("");
    lines.push("Research pilot (opt-in, computed on-device)");
    lines.push(
      `Enrolled: ${pilot.enrolledDay}; endpoint due: ${pilot.endpointDueDay} ` +
      `(${pilot.endpointReached ? "reached" : `${pilot.daysRemaining} days remaining`})`,
    );
    lines.push("Pre/post (baseline -> endpoint):");
    for (const it of pilot.instruments) {
      if (it.baseline && it.endpoint) {
        const dir = it.improved ? "improved" : it.change === 0 ? "no change" : "worsened";
        // Report the RELIABLE-CHANGE band, not just the raw delta. computePilotSummary already
        // classifies every pair against the instrument's MCID (PHQ-9 5 pts / GAD-7 4 pts, cited;
        // WHO-5 10 pts, an engineering default) — but the line below used to print only the point
        // delta and the raw direction, so a 1–2 point PHQ-9 drop was written up as "improved" when
        // it sits inside measurement noise. That is precisely the over-claim the reliableChange
        // field exists to prevent, and this is the artifact a reader judges the pilot by.
        const rc = it.reliableChange;
        const band = !rc
          ? " — no established reliable-change threshold for this instrument"
          : rc.direction === "no_reliable_change"
            ? ` — within measurement noise (<${rc.threshold}-point ${rc.confidence} threshold): not a reliable change`
            : ` — reliable ${rc.direction} (>=${rc.threshold}-point ${rc.confidence} threshold)`;
        lines.push(`- ${it.label}: ${it.baseline.total} -> ${it.endpoint.total} (change ${it.change}, ${dir})${band}`);
      } else if (it.baseline) {
        lines.push(`- ${it.label}: baseline ${it.baseline.total}; endpoint not yet recorded`);
      } else {
        lines.push(`- ${it.label}: no baseline recorded`);
      }
    }
    lines.push("Note: single-arm pre/post — a change is a signal, not proof of effect (no control group).");
  }

  if (feedback && feedback.total > 0) {
    lines.push("");
    lines.push("Your feedback (on-device ratings of Nila replies)");
    lines.push(`Total ratings: ${feedback.total} (${feedback.up} thumbs up, ${feedback.down} thumbs down)`);
    if (feedback.suggestions > 0) lines.push(`Better-reply suggestions shared: ${feedback.suggestions}`);
  }

  lines.push("");
  lines.push(DISCLAIMER);
  return lines.join("\n");
}

export interface ClinicalExportInput {
  generatedAt: string; // ISO — passed in so the builder stays pure/testable
  checkins: CheckInEntry[];
  assessments: AssessmentEntry[];
  retention?: RetentionSummary;
  pilot?: PilotSummary;
  feedback?: FeedbackSummary;
}

/**
 * Build a portable, machine-readable clinical export (JSON). User-initiated and saved to device only, like
 * the CSV/PDF — nothing is transmitted. It carries the *structured* slice a clinician or (with consent) a
 * pilot researcher can ingest without parsing a PDF: the assessment trajectory, a check-in summary, and the
 * on-device retention / pilot summaries. Raw free-text (a check-in's context) is deliberately left to the
 * CSV — this format stays a structured summary. Schema-versioned so downstream parsers can adapt.
 */
export function buildClinicalJson(input: ClinicalExportInput): string {
  const valid = input.checkins.filter((c) => typeof c.intensity === "number");
  const withSleep = valid.filter((c) => typeof c.sleepHours === "number" && (c.sleepHours ?? 0) > 0);
  const dates = input.checkins.map((c) => c.date).filter(Boolean).sort();

  const checkins = {
    count: input.checkins.length,
    averageIntensity: valid.length
      ? +(valid.reduce((s, c) => s + c.intensity, 0) / valid.length).toFixed(1)
      : null,
    averageSleepHours: withSleep.length
      ? +(withSleep.reduce((s, c) => s + (c.sleepHours ?? 0), 0) / withSleep.length).toFixed(1)
      : null,
    firstDate: dates[0] ?? null,
    lastDate: dates[dates.length - 1] ?? null,
  };

  const assessments = input.assessments
    .slice()
    .sort((a, b) => a.date.localeCompare(b.date) || a.timestamp.localeCompare(b.timestamp))
    .map((a) => ({
      instrument: a.instrument,
      date: a.date,
      total: a.total,
      severity: a.severity,
      safetyFlag: a.safetyFlag, // PHQ-9 item 9 endorsed — clinically relevant, stays with the user's data
    }));

  return JSON.stringify(
    {
      schema: "nilamind.clinical-export/v1",
      generatedAt: input.generatedAt,
      disclaimer: DISCLAIMER,
      checkins,
      assessments,
      retention: input.retention ?? null,
      pilot: input.pilot ?? null,
      feedback: input.feedback ?? null,
    },
    null,
    2,
  );
}

// Brand palette shared by every PDF surface (the plain-text report renderer below, and the
// clinician chart dashboard in clinicianPdf.ts) so the two visually match.
export const BRAND: [number, number, number] = [236, 91, 158]; // NilaMind magenta (#EC5B9E)
export const INK: [number, number, number] = [45, 45, 52];
export const MUTE: [number, number, number] = [125, 125, 135];

/** A page's worth of jsPDF drawing state (margins, cursor, pagination), reused by both the
 *  plain-text report renderer (below) and clinicianPdf.ts's chart dashboard so headers, footers,
 *  and pagination behave identically across every PDF NilaMind generates. */
export class PdfCanvas {
  doc: jsPDF;
  pageW: number;
  pageH: number;
  M = 16;
  maxW: number;
  page = 1;
  y = 0;

  constructor(doc: jsPDF) {
    this.doc = doc;
    this.pageW = doc.internal.pageSize.getWidth(); // 210mm
    this.pageH = doc.internal.pageSize.getHeight(); // 297mm
    this.maxW = this.pageW - this.M * 2;
  }

  footer(): void {
    const { doc, pageW, pageH, M, page } = this;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTE);
    doc.text("Generated on-device · Private — not a diagnosis", M, pageH - 8);
    doc.text(String(page), pageW - M, pageH - 8, { align: "right" });
  }

  beginPage(): void {
    this.doc.setFillColor(...BRAND);
    this.doc.rect(0, 0, this.pageW, 2.5, "F"); // top accent bar
    this.y = this.M + 2;
  }

  /** Ensures `h` mm of vertical space remains on the current page, paginating (with footer) if not. */
  ensure(h: number): void {
    if (this.y + h > this.pageH - 14) {
      this.footer();
      this.doc.addPage();
      this.page++;
      this.beginPage();
    }
  }

  /** Explicit page break (used between the chart dashboard and the full-detail text pages). */
  newPage(): void {
    this.footer();
    this.doc.addPage();
    this.page++;
    this.beginPage();
  }
}

const isSep = (s: string) => /^[=\-·—]{3,}$/.test(s.trim());

/** Draws the brand-colored title line(s). Returns nothing; advances canvas.y. */
export function renderTitle(canvas: PdfCanvas, title: string): void {
  const { doc, M, maxW } = canvas;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(...BRAND);
  for (const tl of doc.splitTextToSize(title.trim(), maxW)) {
    canvas.ensure(9);
    doc.text(tl, M, canvas.y);
    canvas.y += 8;
  }
  canvas.y += 1;
}

/** Draws one muted meta line (e.g. the period label under the title). */
export function renderMetaLine(canvas: PdfCanvas, line: string): void {
  const { doc, M, maxW } = canvas;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...MUTE);
  for (const w of doc.splitTextToSize(line, maxW)) {
    canvas.ensure(5);
    doc.text(w, M, canvas.y);
    canvas.y += 4.6;
  }
}

/**
 * Renders the body of a report from `rawLines[fromIndex..]`: col-0 lines are detected as section
 * headers (bold ink + a short magenta accent rule) vs. indented/bulleted body text, matching the
 * structure clinicianReport.ts / buildTextReport emit. Shared by generatePdfBlob and clinicianPdf.ts
 * (the latter reuses it for the full-detail pages that follow the chart dashboard).
 */
export function renderBody(canvas: PdfCanvas, rawLines: string[], fromIndex: number): void {
  const { doc, M, maxW } = canvas;
  for (let i = fromIndex; i < rawLines.length; i++) {
    const line = rawLines[i];
    const trimmed = line.trim();

    if (isSep(trimmed)) { canvas.y += 2.5; continue; }
    if (!trimmed) { canvas.y += 2.5; continue; }

    const indented = /^\s/.test(line);
    // A section header is a col-0 line with no "key: value" and no trailing period (rules out wrapped
    // body continuations like "interactions."), and either short or followed by indented body.
    let j = i + 1;
    while (j < rawLines.length && !rawLines[j].trim()) j++;
    const nextIndented = j < rawLines.length && /^\s/.test(rawLines[j]);
    const isHeader = !indented && !/:\s*\S/.test(trimmed) && !/[.]$/.test(trimmed) && (nextIndented || trimmed.length <= 42);

    if (isHeader) {
      canvas.ensure(12);
      canvas.y += 3.5;
      doc.setFont("helvetica", "bold"); doc.setFontSize(11.5); doc.setTextColor(...INK);
      doc.text(trimmed, M, canvas.y);
      canvas.y += 1.8;
      doc.setDrawColor(...BRAND); doc.setLineWidth(0.5); doc.line(M, canvas.y, M + 20, canvas.y);
      canvas.y += 4;
    } else {
      const indentCols = (line.match(/^\s*/)?.[0].length ?? 0);
      const x = M + Math.min(indentCols, 6) * 1.7;
      doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(...INK);
      for (const w of doc.splitTextToSize(trimmed, maxW - (x - M))) { canvas.ensure(5); doc.text(w, x, canvas.y); canvas.y += 4.8; }
    }
  }
}

/** Splits report text into `{ rawLines, titleIndex, bodyIndex }`: `bodyIndex` is the first line
 *  after the title's meta block and its `---`/`===` separator, ready for `renderBody`. */
export function splitReportText(text: string): { rawLines: string[]; titleIndex: number; bodyIndex: number } {
  const rawLines = text.replace(/\r/g, "").split("\n");
  let titleIndex = rawLines.findIndex((l) => l.trim().length > 0);
  if (titleIndex < 0) titleIndex = 0;
  let bodyIndex = rawLines.length;
  for (let i = titleIndex + 1; i < rawLines.length; i++) {
    if (isSep(rawLines[i].trim())) { bodyIndex = i + 1; break; }
  }
  return { rawLines, titleIndex, bodyIndex };
}

/**
 * Render a report string into a properly formatted, branded PDF (not the old raw line-dump).
 * The report builders (clinicianReport.ts / buildTextReport) emit a consistent structure — a title
 * line, a short meta block, a `---`/`===` separator, then col-0 section headers with indented body
 * lines and `•` bullets — so we style from that: brand title, section headers with a magenta accent
 * rule, muted meta, indented body, and a page footer. Returns null if jsPDF is unavailable.
 */
export function generatePdfBlob(text: string): Blob | null {
  try {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const canvas = new PdfCanvas(doc);
    canvas.beginPage();

    const { rawLines, titleIndex, bodyIndex } = splitReportText(text);
    renderTitle(canvas, rawLines[titleIndex]);
    for (let i = titleIndex + 1; i < bodyIndex - 1; i++) {
      const trimmed = rawLines[i].trim();
      if (!trimmed) { canvas.y += 1.5; continue; }
      renderMetaLine(canvas, trimmed);
    }
    canvas.y += 2.5; // matches the separator's spacing in the original single-pass renderer
    renderBody(canvas, rawLines, bodyIndex);

    canvas.footer();
    return doc.output("blob");
  } catch {
    return null;
  }
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(String(reader.result).split(",")[1] ?? "");
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(blob);
  });
}

/**
 * Persist a report to the device. re-audit #3: the <a download> path silently no-ops inside the Android
 * WebView, so on native (Capacitor) we write to the app's Documents directory via Filesystem — text as UTF-8,
 * the binary PDF as base64. On web/dev we keep the blob-download fallback. Everything stays on-device (no
 * network), consistent with the privacy-first promise.
 */
export async function saveReport(content: string | Blob, filename: string, _mime: string): Promise<boolean> {
  if (Capacitor.isNativePlatform()) {
    try {
      if (typeof content === "string") {
        await Filesystem.writeFile({ path: filename, data: content, directory: Directory.Documents, encoding: Encoding.UTF8, recursive: true });
      } else {
        const base64 = await blobToBase64(content);
        await Filesystem.writeFile({ path: filename, data: base64, directory: Directory.Documents, recursive: true });
      }
      return true;
    } catch (e) {
      console.error("[exportReport] native save failed:", e);
      return false;
    }
  }
  // Web/dev fallback: trigger a blob download.
  try {
    const blob = typeof content === "string" ? new Blob([content], { type: _mime }) : content;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10000);
    return true;
  } catch {
    return false;
  }
}
