// Phase 7 — Clinician-friendly export (PDF + CSV).
// Privacy-first: user-initiated, saved to device only, never sent anywhere.
// Core functions are pure (data in, data out) for testability.

import { jsPDF } from "jspdf";
import type { CheckInEntry } from "../types";

const DISCLAIMER = "Generated by NilaMind — not a clinical or diagnostic tool. For informational use only.";
const CSV_HEADER = "Date,Emotion,Intensity (1-10),Sleep Hours,Context,Granular Emotion";

function escapeCsv(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

/** Build a CSV string from check-in data. Returns header + rows, or empty string when no data. */
export function generateCsvReport(checkins: CheckInEntry[]): string {
  if (!checkins || checkins.length === 0) return "";
  const rows = checkins.map((e) => {
    const date = escapeCsv(e.date ?? "");
    const emotion = escapeCsv((e.emotion ?? "").replace(/ \(Nila\)$/, ""));
    const intensity = e.intensity ?? "";
    const sleepHours = e.sleepHours != null ? String(e.sleepHours) : "";
    const context = escapeCsv(e.context ?? "");
    const granular = escapeCsv(e.granularEmotion ?? "");
    return `${date},${emotion},${intensity},${sleepHours},${context},${granular}`;
  });
  return `${CSV_HEADER}\n${rows.join("\n")}\n\n${DISCLAIMER}`;
}

/** Build a plain-text summary report. */
export function buildTextReport(
  checkins: CheckInEntry[],
  assessmentCount?: number,
): string {
  const lines: string[] = [];
  lines.push("NilaMind Wellness Report");
  lines.push("=".repeat(40));
  lines.push("");

  if (checkins.length > 0) {
    const valid = checkins.filter((c) => typeof c.intensity === "number");
    const avg = valid.length > 0
      ? (valid.reduce((s, c) => s + c.intensity, 0) / valid.length).toFixed(1)
      : "—";
    lines.push(`Total check-ins logged: ${checkins.length}`);
    lines.push(`Average distress intensity: ${avg}/10`);
    const withSleep = valid.filter((c) => typeof c.sleepHours === "number" && c.sleepHours > 0);
    if (withSleep.length > 0) {
      const avgSleep = (withSleep.reduce((s, c) => s + (c.sleepHours ?? 0), 0) / withSleep.length).toFixed(1);
      lines.push(`Average sleep: ${avgSleep}h (${withSleep.length} nights)`);
    }
  } else {
    lines.push("No check-ins recorded yet.");
  }

  if (assessmentCount && assessmentCount > 0) {
    lines.push("");
    lines.push(`Screenings completed: ${assessmentCount}`);
  }

  lines.push("");
  lines.push(DISCLAIMER);
  return lines.join("\n");
}

/** Generate a PDF blob from report text using jsPDF. Returns null if jsPDF is unavailable. */
export function generatePdfBlob(text: string): Blob | null {
  try {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = margin;

    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y > 280) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += 5;
    }
    return doc.output("blob");
  } catch {
    return null;
  }
}

/** Trigger a browser download. Works in browser dev; on-device testing via manual download. */
export async function saveReport(content: string | Blob, filename: string, mime: string): Promise<boolean> {
  try {
    const blob = typeof content === "string" ? new Blob([content], { type: mime }) : content;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10000);
    return true;
  } catch {
    return false;
  }
}
