// Encryption-at-rest core for NilaMind.
//
// Design (chosen with the user): a single random Data-Encryption-Key (DEK, AES-GCM-256) encrypts all
// app data. The DEK itself is never stored in the clear — it is *wrapped* (encrypted) by a
// Key-Encryption-Key (KEK), and only the wrapped blob is persisted:
//
//   • DEFAULT ("device" mode, zero friction): the KEK is a NON-EXTRACTABLE AES-GCM key generated by
//     the Web Crypto API and stored as a CryptoKey object in IndexedDB. JS can use it to unwrap the
//     DEK but can never read its bytes, and it's bound to this app's origin/sandbox. So a casual
//     dump of localStorage/IndexedDB, a device backup, or another app cannot recover the data.
//
//   • OPT-IN ("pin" mode, zero-knowledge): the KEK is derived from the user's PIN via PBKDF2
//     (SHA-256, 250k iterations, random salt). Nothing PIN-derived is stored except the salt and the
//     wrapped DEK. Without the PIN the DEK cannot be unwrapped — true zero-knowledge. Toggling PIN
//     on/off only re-wraps the DEK (no data is ever re-encrypted), and turning PIN ON deletes the
//     device-key path so the device alone can no longer decrypt.
//
// The DEK lives in memory only while the app is open. Plaintext-in-memory is unavoidable (the app
// must use the data); the guarantee is purely about data *at rest*.
//
// Everything here is best-effort and fails SAFE: callers that can't initialise crypto fall back to
// plain storage rather than locking a person out of their safety plan (see secureLocal.ts).

const DB_NAME = "nilamind_secure";
const DB_VERSION = 1;
const SYS_STORE = "sys"; // 'meta' → Meta; 'deviceKey' → CryptoKey (non-extractable)
const KV_STORE = "kv"; // original storage key → EncBlob

const PBKDF2_ITERATIONS = 250_000;

export interface EncBlob {
  iv: string; // base64
  ct: string; // base64
}

interface PinWrap extends EncBlob {
  salt: string; // base64
  iter: number;
}

interface Meta {
  v: number;
  mode: "device" | "pin";
  deviceWrap?: EncBlob; // DEK wrapped under the device KEK (device mode)
  pinWrap?: PinWrap; // DEK wrapped under the PIN-derived KEK (pin mode)
  migratedV?: number; // localStorage→encrypted migration version that has run
}

// ── module state (DEK held only in memory) ──
let dek: CryptoKey | null = null;
let dekBytes: Uint8Array | null = null; // retained in-memory only, to re-wrap when toggling PIN
let meta: Meta | null = null;
let initPromise: Promise<{ mode: "device" | "pin"; unlocked: boolean }> | null = null;

const subtle = () => {
  const c = (globalThis as any).crypto;
  if (!c || !c.subtle) throw new Error("Web Crypto unavailable");
  return c.subtle as SubtleCrypto;
};
const randomBytes = (n: number): Uint8Array => {
  const a = new Uint8Array(n);
  (globalThis as any).crypto.getRandomValues(a);
  return a;
};

const enc = new TextEncoder();
const dec = new TextDecoder();
const b64 = (buf: ArrayBuffer | Uint8Array): string => {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
};
const ub64 = (s: string): Uint8Array => {
  const bin = atob(s);
  const a = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
  return a;
};

// ── IndexedDB helpers ──
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(SYS_STORE)) db.createObjectStore(SYS_STORE);
      if (!db.objectStoreNames.contains(KV_STORE)) db.createObjectStore(KV_STORE);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}
function idbReq<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}
async function idbGet<T>(store: string, key: string): Promise<T | undefined> {
  const db = await openDB();
  try {
    return await idbReq<T>(db.transaction(store, "readonly").objectStore(store).get(key) as IDBRequest<T>);
  } finally {
    db.close();
  }
}
async function idbPut(store: string, key: string, val: any): Promise<void> {
  const db = await openDB();
  try {
    const tx = db.transaction(store, "readwrite");
    tx.objectStore(store).put(val, key);
    await new Promise<void>((res, rej) => {
      tx.oncomplete = () => res();
      tx.onerror = () => rej(tx.error);
      tx.onabort = () => rej(tx.error);
    });
  } finally {
    db.close();
  }
}
async function idbDel(store: string, key: string): Promise<void> {
  const db = await openDB();
  try {
    const tx = db.transaction(store, "readwrite");
    tx.objectStore(store).delete(key);
    await new Promise<void>((res, rej) => {
      tx.oncomplete = () => res();
      tx.onerror = () => rej(tx.error);
    });
  } finally {
    db.close();
  }
}
async function idbAll(store: string): Promise<{ keys: string[]; values: any[] }> {
  const db = await openDB();
  try {
    const os = db.transaction(store, "readonly").objectStore(store);
    const keys = (await idbReq<IDBValidKey[]>(os.getAllKeys() as any)).map(String);
    const values = await idbReq<any[]>(os.getAll() as any);
    return { keys, values };
  } finally {
    db.close();
  }
}

// ── crypto primitives ──
async function wrapDek(kek: CryptoKey, bytes: Uint8Array): Promise<EncBlob> {
  const iv = randomBytes(12);
  const ct = await subtle().encrypt({ name: "AES-GCM", iv }, kek, bytes);
  return { iv: b64(iv), ct: b64(ct) };
}
async function unwrapDek(kek: CryptoKey, blob: EncBlob): Promise<Uint8Array> {
  const pt = await subtle().decrypt({ name: "AES-GCM", iv: ub64(blob.iv) }, kek, ub64(blob.ct));
  return new Uint8Array(pt);
}
async function importDek(bytes: Uint8Array): Promise<CryptoKey> {
  return subtle().importKey("raw", bytes, "AES-GCM", false, ["encrypt", "decrypt"]);
}
async function deriveKekFromPin(pin: string, salt: Uint8Array, iter: number): Promise<CryptoKey> {
  const material = await subtle().importKey("raw", enc.encode(pin), "PBKDF2", false, ["deriveKey"]);
  return subtle().deriveKey(
    { name: "PBKDF2", salt, iterations: iter, hash: "SHA-256" },
    material,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
}

// ── public API ──

/**
 * Initialise crypto. On first ever run, generates the device KEK + DEK and persists the wrapped DEK
 * (device mode). On later runs: device mode unlocks automatically; pin mode returns unlocked=false
 * and the caller must call unlockWithPin(). Idempotent (safe under React StrictMode double-invoke).
 */
export function initSecure(): Promise<{ mode: "device" | "pin"; unlocked: boolean }> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    meta = (await idbGet<Meta>(SYS_STORE, "meta")) ?? null;

    if (!meta) {
      // First run — create everything in device mode.
      const deviceKey = await subtle().generateKey({ name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
      await idbPut(SYS_STORE, "deviceKey", deviceKey);
      dekBytes = randomBytes(32);
      dek = await importDek(dekBytes);
      const deviceWrap = await wrapDek(deviceKey, dekBytes);
      meta = { v: 1, mode: "device", deviceWrap, migratedV: 0 };
      await idbPut(SYS_STORE, "meta", meta);
      return { mode: "device", unlocked: true };
    }

    if (meta.mode === "device" && meta.deviceWrap) {
      const deviceKey = await idbGet<CryptoKey>(SYS_STORE, "deviceKey");
      if (!deviceKey) throw new Error("device key missing");
      dekBytes = await unwrapDek(deviceKey, meta.deviceWrap);
      dek = await importDek(dekBytes);
      return { mode: "device", unlocked: true };
    }

    // pin mode — locked until the user supplies their PIN.
    return { mode: "pin", unlocked: false };
  })();
  return initPromise;
}

export function isUnlocked(): boolean {
  return dek !== null;
}
export function currentMode(): "device" | "pin" | null {
  return meta?.mode ?? null;
}
export function hasPin(): boolean {
  return meta?.mode === "pin";
}

/** Unlock a pin-mode store. Throws on wrong PIN (AES-GCM auth failure). */
export async function unlockWithPin(pin: string): Promise<void> {
  if (!meta || meta.mode !== "pin" || !meta.pinWrap) throw new Error("not in pin mode");
  const { salt, iter } = meta.pinWrap;
  const kek = await deriveKekFromPin(pin, ub64(salt), iter);
  dekBytes = await unwrapDek(kek, meta.pinWrap); // throws if PIN wrong
  dek = await importDek(dekBytes);
}

/** Turn on PIN protection (zero-knowledge). Requires the store be unlocked first. */
export async function setPin(pin: string): Promise<void> {
  if (!dek || !dekBytes) throw new Error("locked");
  const salt = randomBytes(16);
  const kek = await deriveKekFromPin(pin, salt, PBKDF2_ITERATIONS);
  const wrap = await wrapDek(kek, dekBytes);
  const next: Meta = { ...(meta as Meta), mode: "pin", pinWrap: { ...wrap, salt: b64(salt), iter: PBKDF2_ITERATIONS } };
  delete next.deviceWrap;
  await idbDel(SYS_STORE, "deviceKey"); // device alone can no longer decrypt
  await idbPut(SYS_STORE, "meta", next);
  meta = next;
}

/** Turn PIN protection back off (return to frictionless device mode). Requires unlocked. */
export async function removePin(): Promise<void> {
  if (!dek || !dekBytes) throw new Error("locked");
  const deviceKey = await subtle().generateKey({ name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
  await idbPut(SYS_STORE, "deviceKey", deviceKey);
  const deviceWrap = await wrapDek(deviceKey, dekBytes);
  const next: Meta = { ...(meta as Meta), mode: "device", deviceWrap };
  delete next.pinWrap;
  await idbPut(SYS_STORE, "meta", next);
  meta = next;
}

// ── value encryption (used by secureLocal) ──
export async function encryptValue(plaintext: string): Promise<EncBlob> {
  if (!dek) throw new Error("locked");
  const iv = randomBytes(12);
  const ct = await subtle().encrypt({ name: "AES-GCM", iv }, dek, enc.encode(plaintext));
  return { iv: b64(iv), ct: b64(ct) };
}
export async function decryptValue(blob: EncBlob): Promise<string> {
  if (!dek) throw new Error("locked");
  const pt = await subtle().decrypt({ name: "AES-GCM", iv: ub64(blob.iv) }, dek, ub64(blob.ct));
  return dec.decode(pt);
}

// ── kv persistence (encrypted values keyed by the original storage key) ──
export async function kvGetAll(): Promise<Record<string, EncBlob>> {
  const { keys, values } = await idbAll(KV_STORE);
  const out: Record<string, EncBlob> = {};
  keys.forEach((k, i) => (out[k] = values[i]));
  return out;
}
export const kvPut = (key: string, blob: EncBlob) => idbPut(KV_STORE, key, blob);
export const kvDel = (key: string) => idbDel(KV_STORE, key);

// migration bookkeeping
export function migratedVersion(): number {
  return meta?.migratedV ?? 0;
}
export async function setMigratedVersion(v: number): Promise<void> {
  if (!meta) return;
  meta = { ...meta, migratedV: v };
  await idbPut(SYS_STORE, "meta", meta);
}
