// Weekly wellness report card — a concise, on-device PDF-formatted summary of the past 7 days.
// Privacy-first: generated on-device, user-initiated, never sent anywhere.
// Built as plain text for jsPDF consumption (via generatePdfBlob in exportReport.ts).

const SEPARATOR = "-".repeat(40);
const DISCLAIMER = "Generated by NilaMind — not a clinical or diagnostic tool. For informational use only.";

export interface WeeklyReportInput {
  weekEnding: string; // YYYY-MM-DD
  totalCheckins: number;
  daysActive: number; // distinct days with a check-in
  avgIntensity: number | null;
  minIntensity: number | null;
  maxIntensity: number | null;
  topEmotion: string | null;
  avgSleepHours: number | null;
  protocolsCompleted: number;
  nilaSessions: number;
  currentStreak: number;
  longestStreak: number;
  featuresUsed: string[];
  circadianScore: number | null;
}

export function buildWeeklyReport(input: WeeklyReportInput): string {
  const lines: string[] = [];

  lines.push("NilaMind Weekly Report");
  lines.push(`Week ending: ${input.weekEnding}`);
  lines.push(SEPARATOR);
  lines.push("");

  if (input.totalCheckins === 0) {
    lines.push("No check-ins this week. Your dashboard is ready when you are.");
    lines.push("");
    lines.push(SEPARATOR);
    lines.push(DISCLAIMER);
    return lines.join("\n");
  }

  lines.push("Check-ins");
  lines.push(`  Total: ${input.totalCheckins}`);
  lines.push(`  Active days: ${input.daysActive}/7`);

  if (input.avgIntensity != null) {
    lines.push(`  Avg intensity: ${input.avgIntensity.toFixed(1)}/10`);
  }
  if (input.minIntensity != null && input.maxIntensity != null) {
    lines.push(`  Range: ${input.minIntensity}–${input.maxIntensity}`);
  }
  if (input.topEmotion) {
    lines.push(`  Most frequent emotion: ${input.topEmotion}`);
  }
  lines.push("");

  // Sleep
  if (input.avgSleepHours != null) {
    lines.push("Sleep");
    lines.push(`  Avg sleep: ${input.avgSleepHours.toFixed(1)}h`);
    lines.push("");
  }

  // Circadian rhythm
  if (input.circadianScore != null) {
    lines.push("Rhythm stability");
    lines.push(`  Score: ${input.circadianScore}/100`);
    lines.push("");
  }

  // Engagement
  lines.push("Engagement");
  lines.push(`  Protocols completed: ${input.protocolsCompleted}`);
  lines.push(`  Nila sessions: ${input.nilaSessions}`);
  lines.push(`  Current streak: ${input.currentStreak} days`);
  lines.push(`  Longest streak: ${input.longestStreak} days`);

  if (input.featuresUsed.length > 0) {
    lines.push(`  Features used: ${input.featuresUsed.join(", ").replace(/_/g, " ")}`);
  }
  lines.push("");

  lines.push(SEPARATOR);
  lines.push(DISCLAIMER);

  return lines.join("\n");
}
